#!/usr/bin/env python
'''
    PUP: Pedigree UPdater

    Copyright (c) 2010 Matthew Iselin

    Permission to use, copy, modify, and distribute this software for any
    purpose with or without fee is hereby granted, provided that the above
    copyright notice and this permission notice appear in all copies.

    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

    pup: central script for simplicity
'''

import os, sys
from optparse import OptionParser

args = sys.argv

if len(args) < 2:
    print "Usage: pup <operation> <operation_args>"
    exit()

potential_ops = ["makepkg", "regpkg", "sync", "install"]
if not args[1] in potential_ops:
    print "Operation '" + args[1] + "' not supported."
    print "Supported operations: " + ', '.join(potential_ops)
    exit()

script_path = os.path.dirname(args[0])

runscript = "pup-" + args[1]
__import__(runscript)
mod = sys.modules[runscript]

mod.main(args[2:])

