####################################
# SCons build system for Pedigree
## Tyler Kennedy (AKA Linuxhq AKA TkTech)
####################################

import os.path
Import(['env'])

tmp = env.Clone()

# Change to then name of this module
moduledir = "#" + env["PEDIGREE_BUILD_MODULES"]
objname = moduledir + '/config.o'

env.Alias("modules", objname)

# To include a new subdirectory just add to the list.
subdirs = [

]

# To include new files just add to the list, or Glob("*.cpp")
files = [
    Glob("*.cc"),
    Glob("*.c")
]

# To include a new directory for includes, just add it to the list
include = [
    '#/src/system/include/',
    '../',
    '.'
]

# To add a library add to the list below
libraries = [
    'gcc'
]

# To add a library path add to the list below
libpaths = [
    env['LIBGCC']
]

####################################
SConscript([os.path.join(i, 'SConscript') for i in subdirs],exports = ['tmp'])
tmp.objects = [tmp.Object(i) for i in files]
tmp['CPPPATH'] = [i for i in include]
tmp['LIBS'] = [i for i in libraries]
tmp['LIBPATH'] = [i for i in libpaths]
tmp['CFLAGS']  ='-Os -g0 -nostdlib -nostdinc -DSQLITE_OS_OTHER=1 -DSQLITE_THREADSAFE=0 -DSQLITE_TEMP_STORE=3 -DSQLITE_DISABLE_LFS=1 -DSQLITE_OMIT_LOCALTIME=1 -DSQLITE_OMIT_FLOATING_POINT=1';
#^-- Stupid way of doing it but I plan on adding processing.

if not len(files) == 0:
    build = tmp.Program(objname,tmp.objects,LINKFLAGS='-nostdlib -Wl,-r -T $LSCRIPT',LSCRIPT=File("#src/modules/link.ld"))
