####################################
# SCons build system for Pedigree
## Tyler Kennedy (AKA Linuxhq AKA TkTech)
####################################

import os.path
Import(['env'])

# To include a new subdirectory just add to the list.
subdirs = [
    'common',
    'kernel',
    'modules'
    #,'boot'
    # ^-- Need to add ARCH options first
]

SConscript([os.path.join(i, 'SConscript') for i in subdirs],exports = ['env'])