####################################
# SCons build system for Pedigree
## Tyler Kennedy (AKA Linuxhq AKA TkTech)
####################################

import os.path
Import(['env'])

if env['ARCH_TARGET'] == 'ARM':
    subdirs = ['boot', 'kernel']
else:
    subdirs = ['boot', 'common', 'kernel']

SConscript([os.path.join(i, 'SConscript') for i in subdirs],exports = ['env'])
