####################################
# SCons build system for Pedigree
## Tyler Kennedy (AKA Linuxhq AKA TkTech)
####################################

import os.path
Import(['env'])

tmp = env.Clone()

# To include a new subdirectory just add to the list.
subdirs = [
    'applications/apptest',
    'applications/syscall-test',
    'applications/net-test',
#   'applications/netconfig',
    'applications/login',
    'applications/keymap',
    'applications/mount',
    'applications/TUI',
    'applications/config',
    'applications/display-mode',
    'applications/reboot',
    'applications/sudo',
    'applications/modload',
    'applications/modlist'
]

# Cleans a set of flags
def fixFlags(flags):
    flags = flags.replace('-nostdinc', '')
    flags = flags.replace('-ffreestanding', '')
    flags = flags.replace('-nostdlib', '')
    flags += ' -msse2'
    if env['ARCH_TARGET'] == 'PPC':
        flags += ' -U__svr4__ '
    return flags

# Fix the CFLAGS and CXXFLAGS for applications
env['CFLAGS'] = fixFlags(env['CFLAGS'])
env['CXXFLAGS'] = fixFlags(env['CXXFLAGS'])

SConscript([os.path.join(i, 'SConscript') for i in subdirs],exports = ['env'])

# Reset the old environment
env = tmp
