#!/usr/bin/perl

my ($fd, $name);
if ($ARGV[0] =~ m/initrd/) {
  open $fd, ">", "autogen_initrd.h";
  $name = "initrd";
}
else {
  open $fd, ">", "autogen.h";
  $name = "file";
}
print $fd "/* autogenerated by mkheader.pl, do not edit. */\n";
print $fd "uint8_t ".$name."[]  __attribute__((aligned (4096))) = {\n";

open my $in, "<", $ARGV[0];
binmode($in);

$/ = undef;
$_ = <$in>;
@a = split "";
for(@a) {
  printf $fd "0x%02x, ", ord;
  print $fd "\n" unless ++$c % 20
}

print $fd "};\n";

print $fd "const unsigned int ".$name."_size = ". scalar(@a) . ";\n";
