'''
Copyright (c) 2008-2014, Pedigree Developers

Please see the CONTRIB file in the root of the source tree for a full
list of contributors.

Permission to use, copy, modify, and distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
'''

import os
import pipes

Import(['env'])

env_clone = env.Clone()

basedir = "#"
kerneldir = "#" + env["PEDIGREE_BUILD_KERNEL"]
objname = 'bootloader'

files = [
    'boot.s',
    'main.cc',
    'prom.cc',
    'Elf32.cc'
]

env_clone['CPPPATH'] = ['.']

env_clone.Program(objname, files, LINKFLAGS="-T$LSCRIPT",
    LSCRIPT=os.path.join(basedir, "/src/system/boot/ppc/link-arm.ld"))
env_clone.Command("autogen.h", None,
    " ".join(pipes.quote(s) for s in [
        "@perl", os.path.join(basedir, 'src/system/boot/ppc/mkheader.pl'),
        os.path.join(kerneldir, 'kernel')
        ]
    )
)

env.Alias("kernel", objname)
