/*
 * Copyright (c) 2008 James Molloy, Jörg Pfähler, Matthew Iselin
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#ifndef SYSCALL_NUMBERS_H
#define SYSCALL_NUMBERS_H

#define POSIX_OPEN        1
#define POSIX_WRITE       2
#define POSIX_READ        3
#define POSIX_CLOSE       4
#define POSIX_SBRK        5
#define POSIX_FORK        6
#define POSIX_EXECVE      7
#define POSIX_WAITPID     8
#define POSIX_EXIT        9
#define POSIX_OPENDIR    10
#define POSIX_READDIR    11
#define POSIX_REWINDDIR  12
#define POSIX_CLOSEDIR   13
#define POSIX_TCGETATTR  14
#define POSIX_TCSETATTR  15
#define POSIX_IOCTL      16
#define POSIX_STAT       17
#define POSIX_FSTAT      18
#define POSIX_GETPID     19
#define POSIX_CHDIR      20
#define POSIX_SELECT     21
#define POSIX_LSEEK      22

#define POSIX_SOCKET     23
#define POSIX_CONNECT    24
#define POSIX_SEND       25
#define POSIX_RECV       26
#define POSIX_BIND       27
#define POSIX_LISTEN     28
#define POSIX_ACCEPT     29
#define POSIX_RECVFROM   30
#define POSIX_SENDTO     31

#define POSIX_GETTIMEOFDAY 32
#define POSIX_DUP        33
#define POSIX_DUP2       34
#define POSIX_LSTAT      35
#define POSIX_UNLINK     36
#define POSIX_SYMLINK    1000

#define POSIX_GETHOSTBYNAME   37
#define POSIX_GETHOSTBYADDR   38

#define POSIX_FCNTL      39
#define POSIX_PIPE       40

#define POSIX_MKDIR      41
#define POSIX_GETPWENT   42
#define POSIX_GETPWNAM   43
#define POSIX_GETUID     44
#define POSIX_GETGID     45

#define POSIX_SIGACTION  46
#define POSIX_SIGNAL     47
#define POSIX_RAISE      48
#define POSIX_KILL       49
#define POSIX_SIGPROCMASK     50

#define POSIX_ALARM      51
#define POSIX_SLEEP      52

#define POSIX_DLOPEN     53
#define POSIX_DLSYM      54
#define POSIX_DLCLOSE    55

#define POSIX_POLL       56

#define POSIX_RENAME     57

#define POSIX_GETCWD     58

#define POSIX_READLINK   59
#define POSIX_LINK       60

#define POSIX_ISATTY     61

#define POSIX_MMAP       62
#define POSIX_MUNMAP     63

#define POSIX_SHUTDOWN   64

#define POSIX_ACCESS     65

#define POSIX_SETSID     66
#define POSIX_SETPGID    67
#define POSIX_GETPGRP    68

#define POSIX_SIGALTSTACK 69

#define POSIX_SEM_CLOSE     70
#define POSIX_SEM_DESTROY   71
#define POSIX_SEM_GETVALUE  72
#define POSIX_SEM_INIT      73
#define POSIX_SEM_OPEN      74
#define POSIX_SEM_POST      75
#define POSIX_SEM_TIMEWAIT  76
#define POSIX_SEM_TRYWAIT   77
#define POSIX_SEM_UNLINK    78
#define POSIX_SEM_WAIT      79

#define POSIX_PTHREAD_RETURN    80
#define POSIX_PTHREAD_ENTER     81
#define POSIX_PTHREAD_CREATE    82
#define POSIX_PTHREAD_JOIN      83
#define POSIX_PTHREAD_DETACH    84
#define POSIX_PTHREAD_SELF      85
#define POSIX_PTHREAD_KILL      86
#define POSIX_PTHREAD_SIGMASK   87

#define POSIX_PTHREAD_MUTEX_INIT    88
#define POSIX_PTHREAD_MUTEX_DESTROY 89
#define POSIX_PTHREAD_MUTEX_LOCK    90
#define POSIX_PTHREAD_MUTEX_TRYLOCK 91
#define POSIX_PTHREAD_MUTEX_UNLOCK  92

#define POSIX_PTHREAD_KEY_CREATE    93
#define POSIX_PTHREAD_KEY_DELETE    94
#define POSIX_PTHREAD_SETSPECIFIC   95
#define POSIX_PTHREAD_GETSPECIFIC   96
#define POSIX_PTHREAD_KEY_DESTRUCTOR    97

#define POSIX_SYSLOG            98

#define POSIX_FTRUNCATE         99

#define POSIX_STUBBED           100

#define PEDIGREE_LOGIN          101
#define PEDIGREE_SIGRET         102
#define PEDIGREE_INIT_SIGRET    103
#define PEDIGREE_INIT_PTHREADS  104
#define PEDIGREE_LOAD_KEYMAP    105
#define PEDIGREE_GET_MOUNT      106
#define PEDIGREE_REBOOT         107

#define PEDIGREE_CONFIG_GETCOLNAME  108
#define PEDIGREE_CONFIG_GETSTR_N    109
#define PEDIGREE_CONFIG_GETNUM_N    110
#define PEDIGREE_CONFIG_GETBOOL_N   111
#define PEDIGREE_CONFIG_GETSTR_S    112
#define PEDIGREE_CONFIG_GETNUM_S    113
#define PEDIGREE_CONFIG_GETBOOL_S   114
#define PEDIGREE_CONFIG_QUERY       115
#define PEDIGREE_CONFIG_FREERESULT  116
#define PEDIGREE_CONFIG_NUMCOLS     117
#define PEDIGREE_CONFIG_NUMROWS     118
#define PEDIGREE_CONFIG_NEXTROW     119
#define PEDIGREE_CONFIG_WAS_SUCCESSFUL 120
#define PEDIGREE_CONFIG_GET_ERROR_MESSAGE 121

#endif
