####################################
# SCons build system for Pedigree
## Tyler Kennedy (AKA Linuxhq AKA TkTech)
####################################

import os
import shutil
Import(['env'])

# To include a new subdirectory just add to the list.
subdirs = ['SDL-1.2.14']

SConscript([os.path.join(i, 'SConscript') for i in subdirs],exports = ['env'])
