# \author James Molloy
# \date   21-Jan-08

###################################################################
# Subdirectory list.
DIRECTORIES =

###################################################################
# Source file list.
SRCFILES = main2.cc

###################################################################
# Set up environment for buildCommon.mk and call.

BUILD_NAME=kernel

include $(BUILD)/buildCommon.mk

