#!/bin/bash

if [ -f hdd_16h_63spt_100c.img ]; then
  qemu-system-x86_64 -fda floppy.img -hda hdd_16h_63spt_100c.img -hdb hdd_16h_63spt_100c_fat16.img -boot a $*
else
  qemu-system-x86_64 -fda floppy.img -hda hdd_16h_63spt_100c_fat16.img -boot a $*
fi
