#!/bin/sh

#qemu-system-arm -M versatilepb -kernel bootloader -serial /dev/tty
#qemu-system-arm -M integratorcp -kernel bootloader -serial /dev/tty

# linaro beaglexm emulation

qemu-system-arm -M beaglexm -drive if=sd,cache=writeback,file=build/sdcard.img \
    -clock unix -serial stdio -device usb-kbd -usb \
    -drive if=none,id=usbstick,file=build/hdd.img \
    -device usb-storage,drive=usbstick $*
