####################################
# SCons build system for Pedigree
## Tyler Kennedy (AKA Linuxhq AKA TkTech)
####################################

import os.path
Import(['env'])

tmp = env.Clone()

builddir = "#" + env["PEDIGREE_BUILD_BASE"]
kerneldir = "#" + env["PEDIGREE_BUILD_KERNEL"]
appdir = "#" + env["PEDIGREE_BUILD_APPS"]
imagesdir = env["PEDIGREE_IMAGES_DIR"]
objname = appdir + '/TUI'

# Part of the apps target
env.Alias("apps", objname)

# We must be rebuilt if the CRT0 changes, but because libc/libm are shared
# objects there's no need to rebuild if they change - we just require that
# they exist when we build.
env.Depends(objname, "crt0")
env.Requires(objname, "libs")

# To include a new subdirectory just add to the list.
subdirs = [
    
]

# To include new files just add to the list, or Glob("*.cpp")
files = [
    'main.cc',
    'Font.cc',
    'Png.cc',
    'Header.cc',
    '_Xterm.cc',
    'Terminal.cc',
    'environment.cc',
]

# Already-built object files to link
objects = [
#    kerneldir + '/crt0.o'
]

# To include a new directory for includes, just add it to the list
include = [
    '#/src/subsys/posix/include',
    '#/src/modules/system/TUI',
    './include',
    '.'
]

# To add a library add to the list below
libraries = [
    'gcc',
    'c',
    'm',
    'freetype',
    'libpng',
    'libz',
    'kernelrtti'
]

# To add a library path add to the list below
libpaths = [
    env['LIBGCC'],
    builddir,
    imagesdir + 'libraries',
    '.'
]

####################################
SConscript([os.path.join(i, 'SConscript') for i in subdirs],exports = ['tmp'])

tmp['CPPPATH'] = include
tmp['LIBS'] = libraries
tmp['LIBPATH'] = libpaths
tmp.Program(objname, files + objects, LINKFLAGS='')
