####################################
# SCons build system for Pedigree
## Tyler Kennedy (AKA Linuxhq AKA TkTech)
####################################

import os.path
Import(['env'])

tmp = env.Clone()

builddir = "#" + env["PEDIGREE_BUILD_BASE"]
kerneldir = "#" + env["PEDIGREE_BUILD_KERNEL"]
appdir = "#" + env["PEDIGREE_BUILD_APPS"]
objname = appdir + '/TUI'

# Part of the apps target
env.Alias("apps", objname)

# Dependencies
env.Depends(objname, "crt0")
env.Depends(objname, "subsys")
env.Depends(objname, "libs")

# To include a new subdirectory just add to the list.
subdirs = [
    
]

# To include new files just add to the list, or Glob("*.cpp")
files = [
    'main.cc',
    'Font.cc',
    'Png.cc',
    'colourSpace.cc',
    'Header.cc',
    '_Xterm.cc',
    'Terminal.cc',
    'environment.cc',
    'Vt100.cc'
]

# Already-built object files to link
objects = [
    kerneldir + '/crt0.o'
]

# To include a new directory for includes, just add it to the list
include = [
    '#/src/subsys/posix/include',
    '#/src/modules/system/TUI',
    './include',
    '.'
]

# To add a library add to the list below
libraries = [
    'gcc',
    'c',
    'm',
    'freetype-i686.a',
    'libpng-i686.a',
    'libz-i686.a',
]

# To add a library path add to the list below
libpaths = [
    env['LIBGCC'],
    builddir,
    '.'
]

####################################
SConscript([os.path.join(i, 'SConscript') for i in subdirs],exports = ['tmp'])
tmp.objects = [tmp.Object(i) for i in files] + [tmp.File(i) for i in objects]
tmp['CPPPATH'] = [i for i in include]
tmp['LIBS'] = [i for i in libraries]
tmp['LIBPATH'] = [i for i in libpaths]
#^-- Stupid way of doing it but I plan on adding processing.

# tmp['CFLAGS'] += ' -DNEW_XTERM '
# tmp['CXXFLAGS'] += ' -DNEW_XTERM '

if not len(files) == 0:
    build = tmp.Program(objname,tmp.objects,LINKFLAGS='-nostartfiles')
