####################################
# SCons build system for Pedigree
## Tyler Kennedy (AKA Linuxhq AKA TkTech)
####################################

import os.path
Import(['env'])

tmp = env.Clone()

# To include a new subdirectory just add to the list.
subdirs = [
    'cat',
    # 'ls'
]

SConscript([os.path.join(i, 'SConscript') for i in subdirs],exports = ['env'])

# Reset the old environment
env = tmp
