####################################
# SCons build system for Pedigree
## Tyler Kennedy (AKA Linuxhq AKA TkTech)
####################################

import os.path
Import(['env'])

# To include a new subdirectory just add to the list.
subdirs = [
    'system',
    'subsys',
    'modules',
    'user'
]

SConscript([os.path.join(i, 'SConscript') for i in subdirs],exports = ['env'])

rootdir = env.Dir("#").abspath
print rootdir
builddir = env.Dir("#" + env["PEDIGREE_BUILD_BASE"]).abspath

# Build the configuration database (no dependencies)
configdb = env.File(builddir + '/config.db')

# Complete the build - image creation
floppyimg = env.File(builddir + '/floppy.img')

# Disk images go after everything else
env.Depends(floppyimg, 'subsys')
env.Depends(floppyimg, 'kernel')
env.Depends(floppyimg, 'initrd')
env.Depends(floppyimg, 'libs')
env.Depends(floppyimg, 'apps')

env.Command(configdb, None, '@cd ' + rootdir + ' && python ./scripts/buildDb.py')
if env["installer"]:
    env.Command(floppyimg, None, '@echo Building disk images... && cd ' + builddir + ' && bash ../scripts/create_install.sh ' + builddir)
else:
    env.Command(floppyimg, None, '@echo Building disk images... && cd ' + builddir + ' && bash ../scripts/create_images.sh ' + builddir)
